### ISSUE TITLE
Hitting enter doesn't submit (some?) forms

### ISSUE THREAD

**Issue by forevermatt** [silinternational/idp-pw-ui#34]
Use cases:
- [ ] When adding an email address as an alternate recovery method, typing in an email address and hitting `Enter` doesn't submit the form (at least in Firefox), but feels like it should.
- [ ] Hitting `Enter` also doesn't seem to submit the "Verify code" form (also in Firefox) at `/#/recovery-method/verify/...`

**Comment by wcjr** [comment]
fixed in https://github.com/silinternational/idp-pw-ui/commit/d8054fe11284ce9aa221bb8d78f413407fe65de7
