### ISSUE TITLE
Buttons are really tall on "Verify code" form in Firefox

### ISSUE THREAD

**Issue by forevermatt** [silinternational/idp-pw-ui#35]
The "Resend" and "Verify" buttons are taller than they are wide in Firefox:
![tall-buttons](https://user-images.githubusercontent.com/6233204/28384495-f5085164-6c92-11e7-8960-908d6bd0df2f.png)

**Comment by wcjr** [comment]
fixed with deployment of https://github.com/silinternational/idp-pw-ui/releases/tag/2.0.14
