### ISSUE TITLE
Make browser tab title more specific on the login page

### ISSUE THREAD

**Issue by forevermatt** [silinternational/idp-pw-ui#36]
Could we make the page title (shown in the browser tab) more specific on the login page? It's currently just "Login account", but some password managers (like KeePass) let you define rules for auto-typing your credentials, using the program's window title (= page title + browser name, for browsers) to match on. Having a page title that is specific to the IdP would be very helpful.

**Comment by wcjr** [comment]
not part of this codebase, fixed here:  https://github.com/silinternational/simplesamlphp-module-material/commit/1743d9d81c406c7b6213459dbb3c086654ca8261
