### ISSUE TITLE
No visual indicator alternate method was sent

### ISSUE THREAD

**Issue by fillup** [silinternational/idp-pw-ui#5]
When going through a reset and using alternate methods, clicking the button to send to an alternate email sends the email, but nothing is displayed on screen to tell me that.

**Comment by wcjr** [comment]
I have a TODO for this one because I wasn't 100% sure of the flow.  It's sort of a cross between the dialog the user had just seen before choosing ALTERNATES and the "Add recovery method use case".  I was hoping to discuss the UX before implementing this one.  Can you meet about this one?

**Comment by wcjr** [comment]
Thanks for chatting about this, I'll work on it right now.
