### ISSUE TITLE
Unable to enter phone verification code

### ISSUE THREAD

**Issue by fillup** [silinternational/idp-pw-ui#6]
For some reason it is no longer popping up the option to enter a phone verification code after it is sent.

**Comment by wcjr** [comment]
It's not a dialog, it's a new page once the POST is good from the API.  Here's a screenshot after I've entered a good phone number:  
![image](https://cloud.githubusercontent.com/assets/4412848/16744167/c90ec006-477d-11e6-82ad-ace6d06bc81a.png).  Would you mind walking me through what you were doing @fillup ?

**Comment by fillup** [comment]
Duplicate of #5
