### ISSUE TITLE
Consider using Windows-style line endings?

### ISSUE THREAD

**Issue by forevermatt** [silinternational/idp-pw-ui#62]
https://github.com/silinternational/idp-pw-ui/blob/f45bd743c08575fce9dbc6a68f1d81c5fae5f3cf/app/mfa/codes.html#L23

We received feedback that the downloaded backup codes are all strung together on a single line. The details turned out to be users on Windows (but using Chrome) downloading the codes. Since the codes are downloaded as a `.txt` file, Windows by default uses Notepad to open that.

Unfortunately, Notepad requires CRLF line endings (aka. `\r\n`). LF line endings (aka. `\n`) aren't sufficient.

Have we considered using `\r\n` line endings for the downloaded backup codes `.txt` file? Were their disadvantages to doing so? I'm curious whether this would cause any problems for Mac or Linux users... if not, this could be a simple solution.

I suggest this because many users will be on Windows, and the "download" option will be confusing for them. Thoughts? @wcjr

**Comment by fillup** [comment]
Unfortunately I think we need to make this change.

**Comment by wcjr** [comment]
fixed with deployment of https://github.com/silinternational/idp-pw-ui/releases/tag/2.0.14
