### ISSUE TITLE
wording change when attempting a pw reset

### ISSUE THREAD

**Issue by wcjr** [silinternational/idp-pw-ui#63]
# Current wording
Password reset email sent
If your account is found, we will send a reset password email to your primary email address.

Click the link in the email to set your new password.

# Requested wording
Account not found
If your account is found, we will send a reset password email to your primary email address.

Click the link in the email to set your new password.

**Comment by fillup** [comment]
New wording:

Title: Account not found
Body:
An account was not found for the username or email address you provided. Please try again with a different work email address or just your username. If you continue to have problems please contact support at {support email}.

**Comment by wcjr** [comment]
fixed with deployment of https://github.com/silinternational/idp-pw-ui/releases/tag/2.0.14
