### ISSUE TITLE
New view for login errors

### ISSUE THREAD

**Issue by fillup** [silinternational/idp-pw-ui#8]
If an exception occurs on the API side after the user returns from the IdP to log in, I need a route to redirect the user to with a generic message. Proposed route is ```/auth/error```. This page should have the following content:

Sorry, an error occurred while logging in. A notification has been sent to the support team about the problem. Sometimes this issue can clear up on its own so please wait a minute and try again. If the problem persists please let us know by contacting _Support_.

The support link above should display available support options.

**Comment by wcjr** [comment]
Thanks for the content, looks  great.  Feature added in https://github.com/silinternational/idp-pw-ui/commit/74b23317c4586984803f5884a79e998188815441.
